os: linux
language: java
services:
  - docker
env:
  - $DEPLOY_TO_KSZK=false

jobs:
  include:
    - stage: DockerBuild
      script: chmod +x ./pipeline/stages/docker-build.sh && ./pipeline/stages/docker-build.sh
    - stage: DeployToKSZK
      script: sh -c "[ \"$DEPLOY_TO_KSZK\" = \"true\" ] && (chmod +x ./pipeline/stages/deploy-to-kszk.sh && ./pipeline/stages/deploy-to-kszk.sh ) || echo Skipping deploy to KSZK."

install: skip
script: skip