os: linux
language: java
services:
  - docker
env:
  - $DEPLOY_TO_KSZK=false

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - SHORT_COMMIT_HASH=${TRAVIS_COMMIT::7}

  - IMAGE_NAME_CACHE_BUILDER=${DOCKER_USERNAME}/laboschqpa-server:builder
  - IMAGE_NAME_CACHE_FINAL=${DOCKER_USERNAME}/laboschqpa-server
  - IMAGE_NAME_TAG=${DOCKER_USERNAME}/laboschqpa-server:$(date -u +%Y%m%d-%H%M%S)_${SHORT_COMMIT_HASH}

jobs:
  include:
    - stage: DockerPull
    - script: docker pull ${IMAGE_NAME_CACHE_BUILDER} || true
    - script: docker pull ${IMAGE_NAME_CACHE_FINAL} || true
    - stage: DockerBuildCache
    - script: docker build --target=builder_image --cache-from ${IMAGE_NAME_CACHE_BUILDER} -t ${IMAGE_NAME_CACHE_BUILDER} -f docker/Dockerfile-k8s_dev-travis_build .
    - stage: DockerBuildFinal
    - script: docker build --cache-from ${IMAGE_NAME_CACHE_BUILDER} --cache-from ${IMAGE_NAME_CACHE_FINAL} -t ${IMAGE_NAME_CACHE_FINAL} -t ${IMAGE_NAME_TAG} -f docker/Dockerfile-k8s_dev-travis_build .
    - stage: DockerPush
    - script: docker push ${IMAGE_NAME_CACHE_BUILDER}
    - script: docker push ${IMAGE_NAME_CACHE_FINAL}
    - script: docker push ${IMAGE_NAME_TAG}
    - stage: DeployToKSZK
    - script: sh -c "[ \"$DEPLOY_TO_KSZK\" = \"true\" ] && ./pipeline/deploy-to-kszk.sh || echo Skipping deploy to KSZK."

install: skip
script: skip